import { $ } from 'bun';

await $`rm -rf dist`;

// Build library
await Bun.build({
  entrypoints: ['./src/index.ts'],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  naming: '[dir]/[name].js',
  sourcemap: 'external',
  minify: true,
  // Mark peer dependencies and their transitive deps as external
  external: ['@temporalio/*', 'esbuild'],
});

// Build CLI (includes shebang for executable)
await Bun.build({
  entrypoints: ['./src/cli.ts'],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  naming: '[dir]/[name].js',
  sourcemap: 'external',
  minify: false, // Keep CLI readable for debugging
  external: ['@temporalio/*', 'esbuild'],
});

// Build Vite plugin
await Bun.build({
  entrypoints: ['./src/vite-plugin.ts'],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  naming: '[dir]/[name].js',
  sourcemap: 'external',
  minify: true,
  external: ['@temporalio/*', 'esbuild', 'vite'],
});

// Build Bun plugin
await Bun.build({
  entrypoints: ['./src/bun-plugin.ts'],
  outdir: './dist',
  target: 'bun',
  format: 'esm',
  naming: '[dir]/[name].js',
  sourcemap: 'external',
  minify: true,
  external: ['@temporalio/*', 'esbuild'],
});

// Build plugins (file loaders)
await Bun.build({
  entrypoints: [
    './src/plugins/index.ts',
    './src/plugins/text.ts',
    './src/plugins/markdown.ts',
    './src/plugins/toml.ts',
    './src/plugins/yaml.ts',
  ],
  outdir: './dist/plugins',
  target: 'node',
  format: 'esm',
  naming: '[name].js',
  sourcemap: 'external',
  minify: true,
  external: ['@temporalio/*', 'esbuild', 'smol-toml', 'yaml'],
});

await $`bunx tsc --declaration --emitDeclarationOnly --project tsconfig.build.json`;

// Copy types.d.ts to dist (not generated by tsc since it's already .d.ts)
await Bun.write('./dist/types.d.ts', Bun.file('./src/types.d.ts'));

console.log('Build complete!');
